export 'package:filestore/presentation/detail_image/detail_image.screen.dart';
export 'package:filestore/presentation/home/home.screen.dart';
export 'package:filestore/presentation/list_image/list_image.screen.dart';
export 'package:filestore/presentation/login/login.screen.dart';
export 'package:filestore/presentation/post_image/post_image.screen.dart';
export 'package:filestore/presentation/register/register.screen.dart';
export 'package:filestore/presentation/settings/settings.screen.dart';
export 'package:filestore/presentation/splash/splash.screen.dart';
export 'package:filestore/presentation/statistics/statistics.screen.dart';